apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: tomcat
  name: tomcat-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      containers:
      - image: poc2cap/poc2application:latest
        name: tomcat
        ports:
        - name: tomcat
          containerPort: 8010      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tomcat
  name: tomcat
spec:
  type: NodePort
  ports:
    - port: 8010
      targetPort: 8010
  selector:
    name: tomcat
